spring:
  application:
    name: news-summary-api

prompt: You are a news summarizer. Summarize the top global news stories from today in a concise and informative way. Focus on major events, political developments, economic updates, and major technology or science breakthroughs. Keep the summary clear, objective, and easy to read, like a daily news brief.

api:
  news-api:
    key: ${NEWS_APIKEY}
    url:
      base: https://newsapi.org/v2
      content: /top-headlines

  ollama:
    url:
      base: http://127.0.0.1:11434/api
      generate: /generate
      body:
        model: mistral:7b