spring:
  application:
    name: news-summary-api
  profiles:
    active: dev
  ai:
    provider: chatClient # chatClient or apiClient
  cache:
    type: caffeine
    cache-names:
      - news-summaries

api:
  news-api:
    key: ${NEWS_APIKEY}
    url:
      base: https://newsapi.org/v2
      content: /top-headlines
  ollama:
    url:
      base: ${OLLAMA_URL}
      generate: /generate
      body:
        model: mistral:7b